# Generated by Django 6.0.3 on 2026-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
