# Generated by Django 6.0.3 on 2026-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
