# Generated by Django 6.0.3 on 2026-03-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_manager_alter_user_groups_and_more'),
        ('tasks', '0002_alter_orderassignment_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_assignments', to='accounts.user'),
        ),
    ]
