# Generated by Django 6.0.3 on 2026-03-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_orderassignment_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
