# Generated by Django 6.0.3 on 2026-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_orderassignment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
