# Generated by Django 6.0.3 on 2026-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_orderitem_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
