# Generated by Django 6.0.3 on 2026-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_orderitem_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('EMER', 'Emergency')], default='MED', max_length=4),
        ),
    ]
