# Generated by Django 6.0.3 on 2026-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_orderitem_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Pickup'), ('PACKING', 'Packing In-Progress'), ('DAMAGED', 'Marked as Damaged'), ('PACKED', 'Packed & Ready'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
    ]
