# Generated by Django 6.0.3 on 2026-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_orderassignment_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='assignment',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
