# Generated by Django 6.0.3 on 2026-04-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_orderassignment_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_order', to='tasks.orderitem'),
        ),
    ]
