# Generated by Django 6.0.3 on 2026-04-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_orderassignment_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='order',
        ),
    ]
