# Generated by Django 6.0.3 on 2026-05-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10),
        ),
    ]
