# Generated by Django 6.0.3 on 2026-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Pickup'), ('PACKING', 'Packing In-Progress'), ('DAMAGED', 'Marked as Damaged'), ('CANCELLED', 'Cancelled'), ('PACKED', 'Packed & Ready'), ('APPROVED', 'Approved for Shipping'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
    ]
