# Generated by Django 6.0.3 on 2026-04-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_orderassignment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_order', to='tasks.orderitem'),
        ),
    ]
