# Generated by Django 6.0.3 on 2026-04-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_orderassignment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='order',
        ),
    ]
