# Generated by Django 6.0.3 on 2026-05-06 01:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_orderassignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_inspected',
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='issue_status',
            field=models.CharField(choices=[('NONE', 'No Issue'), ('DAMAGED', 'Damaged'), ('MISSING', 'Missing')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('PASSED', 'Verified OK'), ('FAILED', 'Verification Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='tasks.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('ISSUE', 'Issue Found'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
