# Generated by Django 6.0.3 on 2026-05-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_orderitem_is_inspected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
    ]
