# Generated by Django 6.0.3 on 2026-05-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
