# Generated by Django 6.0.3 on 2026-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_orderitem_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='is_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
