# Generated by Django 6.0.3 on 2026-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_orderassignment_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='deadline_packing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
