# Generated by Django 6.0.3 on 2026-06-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.customer'),
        ),
    ]
