# Generated by Django 6.0.3 on 2026-06-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_orderitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Customer',
            new_name='customer',
        ),
    ]
