# Generated by Django 6.0.3 on 2026-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_customer_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deadline_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
