# Generated by Django 6.0.3 on 2026-07-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_orderitem_deadline_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='deadline_date',
            new_name='Shipping_date',
        ),
    ]
