# Generated by Django 6.0.3 on 2026-04-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
