# Generated by Django 6.0.3 on 2026-04-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_systemlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_packing_time_mins',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically calculated average time to pack an order.', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Set to False if staff is on break, off-shift, or at capacity.'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse_zone',
            field=models.ForeignKey(blank=True, help_text='The specialized warehouse area this staff member works in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_staff', to='accounts.department'),
        ),
    ]
