# Generated by Django 6.0.3 on 2026-03-27 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_department_slug_alter_rolepermission_role_and_more'),
        ('inventory', '0002_issuereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='ORD-001', max_length=100, unique=True)),
                ('quantity_to_ship', models.PositiveIntegerField()),
                ('packing_deadline', models.DateTimeField()),
                ('shipping_deadline', models.DateTimeField()),
                ('is_expiry_checked', models.BooleanField(default=False)),
                ('is_damage_verified', models.BooleanField(default=False)),
                ('is_warranty_activated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PACKING', 'In Progress'), ('SHIPPED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('staff_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
