# Generated by Django 6.0.3 on 2026-03-28 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttask',
            name='staff_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
