# Generated by Django 6.0.3 on 2026-03-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_manager_alter_user_groups_and_more'),
        ('shipments', '0002_alter_shipmenttask_staff_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttask',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='shipmenttask',
            name='staff_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tasks', to='accounts.user'),
        ),
    ]
