# Generated by Django 6.0.3 on 2026-03-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_slug_alter_rolepermission_role_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed_by_manager', models.BooleanField(default=False)),
                ('is_escalated_to_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('DAMAGE', 'Damage'), ('OVERDUE', 'Overdue'), ('EXPIRY', 'Expiry')], max_length=20)),
                ('cause', models.CharField(choices=[('HUMAN', 'Human Error'), ('NATURAL', 'Natural/External'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description', models.TextField(help_text='Reason for report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='inventory.product')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
