# Generated by Django 6.0.3 on 2026-03-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_slug_alter_rolepermission_role_and_more'),
        ('inventory', '0002_issuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
