# Generated by Django 6.0.3 on 2026-03-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_manager_alter_user_groups_and_more'),
        ('inventory', '0003_category_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='assigned_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to='accounts.user'),
        ),
    ]
