# Generated by Django 6.0.3 on 2026-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_notification_notification_type_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
