# Generated by Django 6.0.3 on 2026-04-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
