# Generated by Django 6.0.3 on 2026-04-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_issuereport_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('LOW_STOCK', 'Low Stock'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expired'), ('ISSUE', 'Issue Reported')], max_length=20, null=True),
        ),
    ]
