# Generated by Django 6.0.3 on 2026-04-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_notification_is_emergency_and_more'),
        ('requests', '0002_approvalrequest_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bin_location',
            field=models.CharField(default='AISLE-1-A', help_text='Specific warehouse shelf/bin location (e.g., Aisle 4, Shelf B1).', max_length=20),
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ENTRY', 'New Stock Entry'), ('ADJUST', 'Manual Adjustment'), ('EXPIRED', 'Waste: Expired'), ('DAMAGE', 'Waste: Damaged'), ('SHIP', 'Shipped to Client')], max_length=10)),
                ('quantity_changed', models.IntegerField()),
                ('resulting_stock', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.product')),
                ('reference_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.approvalrequest')),
            ],
        ),
    ]
