# Generated by Django 6.0.3 on 2026-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_batch_number_product_bin_location_stocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('OUT_OF_STOCK', 'Out of Stock'), ('DAMAGED', 'Damaged/Quarantine'), ('DISCONTINUED', 'Discontinued')], default='IN_STOCK', max_length=20),
        ),
    ]
