# Generated by Django 6.0.3 on 2026-05-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_tracking_number_alter_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damage_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_damaged',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_to_ship',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipped_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='bin_location',
            field=models.CharField(default='AISLE-1-A', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='action_type',
            field=models.CharField(choices=[('ENTRY', 'New Stock Entry'), ('ADJUST', 'Manual Adjustment'), ('EXPIRED', 'Waste: Expired'), ('DAMAGE', 'Waste: Damaged'), ('SHIP', 'Shipped to Client'), ('QC_FAIL', 'Quality Check Failed'), ('QC_PASS', 'Quality Check Passed')], max_length=10),
        ),
        migrations.CreateModel(
            name='ElectronicsVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('unique_serial_number', models.CharField(max_length=100)),
                ('boot_test_passed', models.BooleanField(default=False)),
                ('ports_physical_ok', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='inventory.product')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('batch_lot', models.CharField(max_length=100)),
                ('temp_chain_ok', models.BooleanField(default=True)),
                ('packaging_sealed', models.BooleanField(default=True)),
                ('fssai_verified', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='inventory.product')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FurnitureVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('structural_ok', models.BooleanField(default=True)),
                ('finish_no_scratches', models.BooleanField(default=True)),
                ('parts_complete', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='inventory.product')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationeryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('quantity_reconciled', models.BooleanField(default=True)),
                ('ink_lead_test_passed', models.BooleanField(default=True)),
                ('paper_not_damaged', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='inventory.product')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
