# Generated by Django 6.0.3 on 2026-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_options_remove_product_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsverification',
            name='unique_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
