# Generated by Django 6.0.3 on 2026-05-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_notification_user'),
        ('tasks', '0009_remove_orderitem_is_inspected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='tasks.orderassignment'),
        ),
    ]
