# Generated by Django 6.0.3 on 2026-05-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_issuereport_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='committed_stock',
            field=models.IntegerField(default=0, help_text='Items reserved for orders not yet shipped'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=0, help_text='Physical items currently in the warehouse'),
        ),
    ]
