# Generated by Django 6.0.3 on 2026-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_committed_stock_alter_product_total_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manager_deadline',
        ),
        migrations.AlterField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, default='AISLE-1-A', max_length=20, null=True),
        ),
    ]
