# Generated by Django 6.0.3 on 2026-05-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_product_manager_deadline_and_more'),
        ('tasks', '0010_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronics_verifications', related_query_name='electronics_verification', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='foodverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_verifications', related_query_name='food_verification', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='furnitureverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furniture_verifications', related_query_name='furniture_verification', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='stationeryverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationery_verifications', related_query_name='stationery_verification', to='tasks.orderassignment'),
        ),
    ]
