# Generated by Django 6.0.3 on 2026-05-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_electronicsverification_assignment_and_more'),
        ('tasks', '0010_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tasks.orderassignment'),
        ),
        migrations.AlterField(
            model_name='foodverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tasks.orderassignment'),
        ),
        migrations.AlterField(
            model_name='furnitureverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tasks.orderassignment'),
        ),
        migrations.AlterField(
            model_name='stationeryverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tasks.orderassignment'),
        ),
    ]
