# Generated by Django 6.0.3 on 2026-05-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_electronicsverification_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicsverification',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='foodverification',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='furnitureverification',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='stationeryverification',
            name='assignment',
        ),
    ]
