# Generated by Django 6.0.3 on 2026-05-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_electronicsverification_assignment_and_more'),
        ('tasks', '0011_alter_orderitem_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_verifications', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='foodverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_verifications', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='furnitureverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_verifications', to='tasks.orderassignment'),
        ),
        migrations.AddField(
            model_name='stationeryverification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_verifications', to='tasks.orderassignment'),
        ),
    ]
