# Generated by Django 6.0.3 on 2026-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_notification_created_by_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
    ]
