"""
Django settings for NexusInventory project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
import os

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=tjtb(#tsp413wue29y(xp%!*u)9w0w)k2qxo0su$cz^4h7^d$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    
    'daphne',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'corsheaders',
    'app.accounts.apps.AccountsConfig',
    'app.reports.apps.ReportsConfig',
    'app.requests.apps.RequestsConfig',
    'app.shipments.apps.ShipmentsConfig',
    'app.Chat.apps.ChatConfig',
    'app.inventory.apps.InventoryConfig',
    'app.tasks.apps.TasksConfig',
    
]



ASGI_APPLICATION = 'NexusInventory.asgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication', # If using JWT
        'rest_framework.authentication.SessionAuthentication',
    ],
'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend',
    #     'rest_framework.filters.SearchFilter',               
    #     'rest_framework.filters.OrderingFilter',         
    # ],


}

CELERY_BEAT_SCHEDULE = {
    'check-stock-every-hour': {
        'task': 'app.inventory.tasks.monitor_inventory_health',  # ✅ fixed duplicate 'task'
        'schedule': 3600.0,  # every 1 hour
    },

    'daily-expiry-check': {
        'task': 'app.inventory.tasks.monitor_inventory_health',  # ✅ use correct existing task
        'schedule': crontab(hour=0, minute=0),  # every midnight
    },

    'monitor-overdue-tasks-every-hour': {
        'task': 'app.inventory.tasks.process_overdue_tasks',  # ✅ correct task name
        'schedule': 3600.0,
    },

    'update-notifications-every-30-mins': {
        'task': 'app.inventory.tasks.update_manager_notification_counts',
        'schedule': 1800.0,  # every 30 minutes
    },

    'daily-manager-report': {
        'task': 'app.inventory.tasks.send_daily_department_report',
        'schedule': crontab(hour=8, minute=0),  # 8:00 AM daily
        'args': (1,),  # department ID
    },
}
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # Add this line!
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' 

CACHES = {

    "default": {

        "BACKEND": "django_redis.cache.RedisCache",

        "LOCATION": "redis://127.0.0.1:6379/1",

        "OPTIONS": {

            "CLIENT_CLASS": "django_redis.client.DefaultClient",

        }

    }

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NexusInventory.urls'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173","http://localhost:3000",
    "http://127.0.0.1:5173",'http://127.0.0.1:300',

]

CORS_ALLOW_ALL_ORIGINS =True

# settings.py
AUTH_USER_MODEL = 'accounts.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NexusInventory.wsgi.application'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER = 'hibashareefamk@gmail.com'
EMAIL_HOST_PASSWORD = 'mjbdvbwpkgciztgv'
DEFAULT_FROM_EMAIL = 'Nexus Inventory nexus@gmail.com'
ADMIN_EMAIL = 'admin@nexus.com'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'nexus_inventory_db',
        'USER':'postgres',
        'PASSWORD':'@hiba#123',
        'HOST':'localhost',
        'PORT':'5432',


    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60*60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=84),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
