# Generated by Django 6.0.3 on 2026-08-30 02:13

import app.Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.Chat.models.chat_file_upload_path),
        ),
    ]
